version: '3.9'

name: vite_docker

services:
  # Port: 4000
  vite:
    build: .
    # command: 'npm run dev'
    tty: true
    image: node:latest
    ports:
      - 3030:3030
    volumes:
      - .:/home/app